# Generated by Django 5.2.8 on 2025-11-22 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='producto',
            new_name='producto_slug_d74905_idx',
            old_name='productos_p_slug_5e4b6d_idx',
        ),
        migrations.RenameIndex(
            model_name='producto',
            new_name='producto_sku_932bd6_idx',
            old_name='productos_p_sku_610a4c_idx',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='producto',
        ),
    ]
